# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haoxilu.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Richard Hao
user_description: Ruby Engineer
user_title: 爱生活，更爱编程！
email: mail@haoxilu.net

# 备案号
casenumber: 京ICP备15036713号

# Google Analytics
ga_track_id: 'UA-70611530-1'            # Format: UA-xxxxxx-xx
ga_domain: haoxilu.net

disqus_username:   haoxilu123

RSS: true
weibo_username:    haoxilu
github_username:   haoxilu
twitter_username:  haoxilu
facebook_username: haoxilu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# enable ssl
enforce_ssl: "haoxilu.net"

# 404
permalink: /404.html

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
