# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 爱编程，更爱生活！！
email: mail@haoxilu.net
description: > # this means to ignore newlines until "baseurl:"
  “爱编程，更爱生活。”是我现在的口号，之前的口号是“ILife，ICode！！爱生活，爱编程！！”，不同之处是现在把生活放到了重要的位置。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://haoxilu.net" # the base hostname & protocol for your site
enforce_ssl:"haoxilu.net"
twitter_username: haoxilu
github_username:  haoxilu

# Build settings
markdown: kramdown

encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink:     pretty
paginate_path: /page:num
timezone:      null
